[project]
description = "Dynamic Ansible Inventory Generator
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "typer>=0.13.1",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
name = "invgen"
version = "0.1.0"
